name: Ci

on: push

jobs:
  DevBuild:
    name: Build the dev version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/Checkout@v2

      - name: Build
        run: ./gradlew build -x test

      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: Dev-Build
          path: build/

      - name: Get the version
        run: |
          while read line; do
              if [[ "$line" =~ version\ .+ ]]
              then
                  VERSION=${line:9}
                  VERSION=${VERSION::-1}
              fi
          done < build.gradle
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Checkout destination repo
        uses: actions/Checkout@v2
        with:
          repository: RecraftedCivilizations/RecraftedCivilizations.github.io
          ssh-key: ${{ secrets.SSH_KEY }}
          path: ./temp

      - name: Copie the files
        run: |
          if [ -d "./temp/Projects/${{ github.REPOSITORY}}/dev-builds/$VERSION" ]
          then
              echo "Deleting old artifacts for the same version"
              rm -rf ./temp/Projects/${{ github.REPOSITORY}}/dev-builds/$VERSION
          fi
          mkdir -p ./temp/Projects/${{ github.REPOSITORY }}/dev-builds/$VERSION
          cp -r build/libs/. ./temp/Projects/${{ github.REPOSITORY }}/dev-builds/$VERSION
      - name: Push the changes
        working-directory: ./temp
        run: |
          git config --global user.name "RecraftedCivilizationsCI"
          git config --global user.email "recrafted-cd@recraftedcivilizations.com"
          git pull --ff
          git add .
          git commit -m "feat: Upload dev-build artifacts results for version: $VERSION"
          git push
  Test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [DevBuild]

    steps:
      - name: Checkout code
        uses: actions/Checkout@v2

      - name: Download the dev build
        uses: actions/download-artifact@master
        with:
          name: Dev-Build
          path: build/

      - name: Run the tests
        run: ./gradlew test

      - name: Get the version
        run: |
          while read line; do
              if [[ "$line" =~ version\ .+ ]]
              then
                  VERSION=${line:9}
                  VERSION=${VERSION::-1}
              fi
          done < build.gradle
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Checkout destination repo
        uses: actions/Checkout@v2
        with:
          repository: RecraftedCivilizations/RecraftedCivilizations.github.io
          ssh-key: ${{ secrets.SSH_KEY }}
          path: ./temp

      - name: Copie the files
        run: |

          if [ -d "./temp/Projects/${{ github.REPOSITORY}}/tests/$VERSION" ]
          then
                  echo "Deleting old tests for the same version"
                  rm -rf ./temp/Projects/${{ github.REPOSITORY}}/tests/$VERSION
          fi
          mkdir -p ./temp/Projects/${{ github.REPOSITORY }}/tests/$VERSION

          cp -r build/reports/tests/test/. ./temp/Projects/${{ github.REPOSITORY }}/tests/$VERSION


      - name: Push the changes
        working-directory: ./temp
        run: |
          git config --global user.name "RecraftedCivilizationsCI"
          git config --global user.email "recrafted-ci@recraftedcivilizations.com"
          git add .
          git commit -m "feat: Upload test results for: $VERSION"
          git push
      - name: Upload test results
        uses: actions/upload-artifact@master
        with:
          name: test-results
          path: build/reports/tests/test

  ProdBuild:
    name: Create Production build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/Checkout@v2

      - name: Build
        run: ./gradlew shadowJar -x test
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: Prod-Build
          path: build/

      - name: Get the version
        run: |
          while read line; do
              if [[ "$line" =~ version\ .+ ]]
              then
                  VERSION=${line:9}
                  VERSION=${VERSION::-1}
              fi
          done < build.gradle
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Checkout destination repo
        uses: actions/Checkout@v2
        with:
          repository: RecraftedCivilizations/RecraftedCivilizations.github.io
          ssh-key: ${{ secrets.SSH_KEY }}
          path: ./temp

      - name: Copie the files
        run: |
          if [ -d "./temp/Projects/${{ github.REPOSITORY}}/prod-builds/$VERSION" ]
          then
              echo "Deleting old artifacts for the same version"
              rm -rf ./temp/Projects/${{ github.REPOSITORY}}/prod-builds/$VERSION
          fi
          mkdir -p ./temp/Projects/${{ github.REPOSITORY }}/prod-builds/$VERSION
          cp -r build/libs/. ./temp/Projects/${{ github.REPOSITORY }}/prod-builds/$VERSION
      - name: Push the changes
        working-directory: ./temp
        run: |
          git config --global user.name "RecraftedCivilizationsCI"
          git config --global user.email "recrafted-cd@recraftedcivilizations.com"
          sleep 15
          git pull --ff
          git add .
          git commit -m "feat: Upload prod-build artifacts results for version: $VERSION"
          git pull --ff
          git push
  Docs:
    name: Generate Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/Checkout@v2
      - name: Generate docs
        run: ./gradlew dokkaHtml
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: Docs
          path: build/dokka/
      - name: Get the version
        run: |
          while read line; do
              if [[ "$line" =~ version\ .+ ]]
              then
                  VERSION=${line:9}
                  VERSION=${VERSION::-1}
              fi
          done < build.gradle
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Checkout destination repo
        uses: actions/Checkout@v2
        with:
          repository: RecraftedCivilizations/RecraftedCivilizations.github.io
          ssh-key: ${{ secrets.SSH_KEY }}
          path: ./temp

      - name: Copie the files
        run: |
          if [ -d "./temp/Projects/${{ github.REPOSITORY}}/docs/$VERSION" ]
          then
              echo "Deleting old artifacts for the same version"
              rm -rf ./temp/Projects/${{ github.REPOSITORY}}/docs/$VERSION
          fi
          mkdir -p ./temp/Projects/${{ github.REPOSITORY }}/docs/$VERSION
          cp -r build/dokka/html/. ./temp/Projects/${{ github.REPOSITORY }}/docs/$VERSION
      - name: Push the changes
        working-directory: ./temp
        run: |
          git config --global user.name "RecraftedCivilizationsCI"
          git config --global user.email "recrafted-cd@recraftedcivilizations.com"
          git pull --ff
          git add .
          git commit -m "feat: Upload prod-build artifacts results for version: $VERSION"
          git push